src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="EMAIL_EXISTS")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fiscal_code;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $job;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $hobbies;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="users")
     */
    private $tags;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $driving_licence;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $privacy_email;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $privacy_phone;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $privacy_address;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $terms_acceptance;

    /**
     * @ORM\ManyToMany(targetEntity=Skill::class, inversedBy="users")
     */
    private $skills;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="userFrom", orphanRemoval=true)
     */
    private $sentTransactions;

    /**
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="userTo", orphanRemoval=true)
     */
    private $receivedTransactions;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=Activity::class, mappedBy="createUser", orphanRemoval=true)
     */
    private $createdActivities;

    /**
     * @ORM\OneToMany(targetEntity=Activity::class, mappedBy="acceptedUser")
     */
    private $acceptedActivities;

    /**
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="createUser")
     */
    private $transactions;

    /**
     * @ORM\OneToMany(targetEntity=Notification::class, mappedBy="user")
     */
    private $notifications;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     */
    private $_del;

    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $createTimestamp;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":1})
     */
    private $commentsEmail = 1;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":1})
     */
    private $activitiesEmail = 1;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     */
    private $rating = 0;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->skills = new ArrayCollection();
        $this->sentTransactions = new ArrayCollection();
        $this->receivedTransactions = new ArrayCollection();
        $this->createdActivities = new ArrayCollection();
        $this->acceptedActivities = new ArrayCollection();
        $this->transactions = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }

    public function __toString(): String
    {
        return $this->name." ".$this->surname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFiscalCode(): ?string
    {
        return $this->fiscal_code;
    }

    public function setFiscalCode(?string $fiscal_code): self
    {
        $this->fiscal_code = $fiscal_code;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(?string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(?string $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getHobbies(): ?string
    {
        return $this->hobbies;
    }

    public function setHobbies(?string $hobbies): self
    {
        $this->hobbies = $hobbies;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tags): self
    {
        if (!$this->tags->contains($tags)) {
            $this->tags[] = $tags;
        }

        return $this;
    }

    public function removeTag(Tag $tags): self
    {
        if ($this->tag->contains($tags)) {
            $this->tag->removeElement($tags);
        }

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getDrivingLicence(): ?bool
    {
        return $this->driving_licence;
    }

    public function setDrivingLicence(bool $driving_licence): self
    {
        $this->driving_licence = $driving_licence;

        return $this;
    }

    public function getPrivacyEmail(): ?bool
    {
        return $this->privacy_email;
    }

    public function setPrivacyEmail(?bool $privacy_email): self
    {
        $this->privacy_email = $privacy_email;

        return $this;
    }

    public function getPrivacyPhone(): ?bool
    {
        return $this->privacy_phone;
    }

    public function setPrivacyPhone(?bool $privacy_phone): self
    {

src/Controller/Restricted/UserProfileController.php
<?php


namespace App\Controller\Restricted;

use App\Entity\Notification;
use App\Entity\User;
use App\Form\UserType;
use App\Helper\UserHelper;
use App\Repository\ActivityRepository;
use App\Repository\BankRepository;
use App\Repository\NotificationRepository;
use App\Repository\SkillRepository;
use App\Repository\TagRepository;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Translation\Translator;
use Symfony\Contracts\Translation\TranslatorInterface;

class UserProfileController extends AbstractController
{
    private $tagRepository;
    private $skillRepository;

    /**
     * RestrictedController constructor.
     * @param $tagRepository
     * @param $skillRepository
     */
    public function __construct(TagRepository $tagRepository, SkillRepository $skillRepository)
    {
        $this->tagRepository = $tagRepository;
        $this->skillRepository = $skillRepository;
    }

    /**
     * @Route("/restricted/user-profile", name="app_user_profile", methods={"GET"})
     */
    public function profile(UserHelper $userHelper, NotificationRepository $notificationRepository)
    {
        $user = $this->getUser();
        $skills = $this->skillRepository->findAll();
        $tags = $this->tagRepository->findAll();
        $form = $this->createForm(UserType::class, $user);

        $statistics = $userHelper->computeStatitics($user);

        //Get latest notifications for this user
        $notifications = $notificationRepository->findBy(["user"=>$user,'dismissed'=>false],["id"=>"desc"]);

        return $this->render('restricted/user-profile/index.html.twig', [
            'user' => $user,
            'notifications'=>$notifications,
            'skills' => $skills,
            'tags' => $tags,
            'form' => $form->createView(),
            'statistics' => $statistics,
            'passwordChanged' => false
        ]);
    }

    /**
     * @Route("/restricted/user-profile", name="post_user_profile", methods={"POST"})
     * @param Request $request
     */
    public function post_profile(
        Request $request,
        BankRepository $bankRepository,
        TranslatorInterface $translator,
        UserPasswordEncoderInterface $passwordEncoder,
        UserHelper $userHelper,
        NotificationRepository $notificationRepository, MailerInterface $mailer
    )
    {
        $user = $this->getUser();
        $skills = $this->skillRepository->findAll();
        $tags = $this->tagRepository->findAll();
        $statistics = $userHelper->computeStatitics($user);

        //Get latest notifications for this user
        $notifications = $notificationRepository->findBy(["user"=>$user,'dismissed'=>false],["id"=>"desc"]);

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        $passwordChanged = false;
        if ($form->isSubmitted() && $form->isValid()) {

            if(
                !is_null($form->get('plainPassword')->getData())
                && !empty($form->get('plainPassword')->getData())
            ){
                // encode the plain password
                $user->setPassword(
                    $passwordEncoder->encodePassword(
                        $user,
                        $form->get('plainPassword')->getData()
                    )
                );

                $passwordChanged = true;

                $bank = $bankRepository->find(1);
                $email = (new TemplatedEmail())
                    ->from(new Address($bank->getSenderEmail(), $bank->getSenderName()))
                    ->to($user->getEmail())
                    ->subject($translator->trans('RESET_PASSWORD_SUCCESS_EMAIL_TITLE'))
                    ->htmlTemplate('restricted/user-profile/email.html.twig')
                    ->context([
                        'user' => $user,
                    ])
                ;

                $mailer->send($email);
            }

            $this->getDoctrine()->getManager()->persist($user);
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->render('restricted/user-profile/index.html.twig', [
            'user' => $user,
            'notifications'=>$notifications,
            'skills' => $skills,
            'tags' => $tags,
            'form' => $form->createView(),
            'statistics' => $statistics,
            'passwordChanged' => $passwordChanged
        ]);
    }

    /**
     * @Route("/restricted/user-profile-delete", name="delete_user_profile", methods={"DELETE"})
     */
    public function delete(Request $request): Response
    {
        $deleteUser = $this->getUser();

        if ($this->isCsrfTokenValid('delete'.$deleteUser->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();

            $uniqueId = uniqid(); //anonimize user
            $deleteUser->setEmail("user" . $uniqueId . "@bdtpavia.com");
            $deleteUser->setName("user" . $uniqueId);
            $deleteUser->setSurname("user" . $uniqueId);
            $deleteUser->setFiscalCode("user" . $uniqueId);
            $deleteUser->setAddress(null);
            $deleteUser->setCity(null);
            $deleteUser->setCountry(null);
            $deleteUser->setZipCode(null);
            $deleteUser->setDescription(null);
            $deleteUser->setPhone(null);
            $deleteUser->setPicture(null);
            $deleteUser->setBirthDate(null);
            $deleteUser->setDel(1); //logic delete
            $entityManager->persist($deleteUser);
            $entityManager->flush();

            return $this->redirectToRoute('app_logout');
        }
    }

    /**
     * @Route("/restricted/member-profile/{id}", name="app_member_profile", methods={"GET"})
     */
    public function member(
        User $member,
        UserHelper $userHelper,
        ActivityRepository $activityRepository,
        NotificationRepository $notificationRepository)
    {
        $user = $this->getUser();

        if($member->getId()==$user->getId()){
            return $this->redirectToRoute('app_user_profile');
        }

        $statistics = $userHelper->computeStatitics($user);
        $memberStatistics = $userHelper->computeStatitics($member);

        //Get latest notifications for this user
        $notifications = $notificationRepository->findBy(["user"=>$user,'dismissed'=>false],["id"=>"desc"]);

        $activities = $activityRepository->getCommonActivities($user,$member);

        return $this->render('restricted/member-profile/index.html.twig', [
            'user' => $user,
            'statistics' => $statistics,
            'member' => $member,
            'memberStatistics' => $memberStatistics,
            'notifications'=>$notifications,
            'passwordChanged' => false,
            'activities' => $activities
        ]);
    }

}

templates/restricted/user-profile/partials/address.profile.html.twig
<!-- Address -->
<div class="row align-items-center">
    <div class="col-8">
        <h6 class="heading-small text-muted mb-0">{{ 'PROFILE_PAGE_SUBTITLE_3'|trans }}</h6>
        <p class="profile-hint">{{ 'PROFILE_PAGE_ADDRESS_HINT'|trans }}</p>
    </div>
    <div class="col-4 text-right">
        <a href="javascript:void(0)" class="btn btn-sm btn-success save-user">{{ 'PROFILE_PAGE_SAVE'|trans }}</a>
    </div>
</div>
<div class="pl-lg-4">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group focused">
                <label class="form-control-label">{{ 'ADDRESS'|trans }}</label>
                {{ form_row(form.address, {'attr': {'class': 'form-control form-control-alternative'}}) }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group focused">
                <label class="form-control-label">{{ 'CITY'|trans }}</label>
                {{ form_row(form.city, {'attr': {'class': 'form-control form-control-alternative'}}) }}
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group focused">
                <label class="form-control-label">{{ 'STATE'|trans }}</label>
                {{ form_row(form.country, {'attr': {'class': 'form-control form-control-alternative'}}) }}
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="form-control-label">{{ 'ZIP_CODE'|trans }}</label>
                {{ form_row(form.zip_code, {'attr': {'class': 'form-control form-control-alternative'}}) }}
            </div>
        </div>
    </div>
</div>

templates/restricted/user-profile/partials/card.profile.html.twig
<div class="card card-profile shadow">
    <div class="row justify-content-center">
        <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
                <a href="{{path('app_user_profile')}}">
                    <div class="rounded-circle profile-picture big" style="background:url({{ user.picture }})">
                        {% if (user is defined and user.picture is null) %}
                            <i class="fa fa-user"></i>
                        {% endif %}
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <!--
        <div class="d-flex justify-content-between">
            <a href="#" class="btn btn-sm btn-info mr-4"></a>
            <a href="#" class="btn btn-sm btn-default float-right"></a>
        </div>
        -->
    </div>
    <div class="card-body pt-0 pt-md-4">
        <div class="row card-profile-stats mt-md-5">
            <div class="col-lg-4">
                <span class="heading">{{ statistics.transactions.sent }} {% if statistics.transactions.sent==1 %}{{ 'UNIT'|trans }}{% else %}{{ 'UNITS'|trans }}{% endif %}</span>
                <span class="description">Spese</span>
            </div>
            <div class="col-lg-4">
                <span class="heading">{{ statistics.transactions.received }} {% if statistics.transactions.received==1 %}{{ 'UNIT'|trans }}{% else %}{{ 'UNITS'|trans }}{% endif %}</span>
                <span class="description">Ricevute</span>
            </div>
            <div class="col-lg-4 credit-highlight">
                <a href="{{ path('app_credit') }}">
                    <span class="heading">{{ statistics.transactions.credit }} {% if statistics.transactions.credit==1 %}{{ 'UNIT'|trans }}{% else %}{{ 'UNITS'|trans }}{% endif %}</span>
                    <span class="description">Credito</span>
                </a>
            </div>
        </div>
        <div class="row card-profile-stats">
            <div class="col-lg-4">
                <span class="heading">{{ statistics.activities.asked }} {{ 'ACTIVITIES'|trans }}</span>
                <span class="description">Richieste</span>
            </div>
            <div class="col-lg-4">
                <span class="heading">{{ statistics.activities.done }}  {{ 'ACTIVITIES'|trans }}</span>
                <span class="description">Eseguite</span>
            </div>
            <div class="col-lg-4">
                <span class="heading">{{ statistics.activities.involved }}  {{ 'ACTIVITIES'|trans }}</span>
                <span class="description">Partecipate</span>
            </div>
        </div>
        <div class="text-center">
            {% if user.birthDate is not null %}
                <h3>
                    {{ user.name }} {{ user.surname }}<span class="font-weight-light">, {{ date('now').diff((date(user.birthDate))).format('%y anni') }}</span>
                </h3>
            {% endif %}
            <div class="h5 font-weight-300">
                {{ user.description }}
            </div>
            <div class="h5 mt-4">
                {{ user.job }}
            </div>
            <div class="user-points-container" style="border: 1px solid #192539;border-radius:10px;background:#192539;color:white;margin-top:-20px;margin-bottom:10px">
                <span class="user-points">{{ statistics.level.points }}p</span>
                {% if statistics.rating>0 %}|&nbsp;<i class="fa fa-medal"></i>&nbsp;{{ statistics.rating }}&nbsp;{% endif %}
                |&nbsp;<i class="fa {{ statistics.level.icon }}"></i>&nbsp;<span>{{ statistics.level.extended }}</span>
            </div>
            <div class="user-points-hint" style="font-size:15px;text-align:justify">
                <span>In questo box puoi vedere i tuoi punti (<b>{{ statistics.level.points }}p</b>){% if statistics.rating>0 %}, la tua reputazione (<b>{{ statistics.rating  }}</b> medaglie){% endif %} e il tuo attuale livello (<b>{{ statistics.level.extended }}</b>).</span>
                <span>Queste informazioni indicano agli altri utenti il tuo grado di partecipazione alla piattaforma.</span>
                <span>Al crescere dei punti ti verrà assegnato un livello superiore, in modo che la tua reputazione aumenti di conseguenza alle azioni che fai sulla Banca del Tempo.</span>
                {% if statistics.level.next is not null %}
                    <span><b>Il prossimo livello che puoi raggiungere è {{ statistics.level.next }}, quando otterrai {{ statistics.level.limit }} punti.</b></span>
                {% endif %}
                <span>Sono assegnati 10 punti per ogni attività eseguita e 5 punti per ogni attività che hai ricevuto.</span>
                <span><b>Gli utenti possono assegnarti delle medaglie per aumentare la tua reputazione</b>: ricordati di chiedere un feedback sulle attività che svolgi!</span>
            </div>

        </div>
    </div>
</div>

templates/restricted/user-profile/partials/delete.form.profile.html.twig
<form id="delete-profile-form" method="post" action="{{ path('delete_user_profile')}}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
</form>

templates/restricted/user-profile/partials/delete.profile.html.twig
<div class="card card-profile shadow">
    <div class="row align-items-center" style="margin-left: 10px;margin-top: 10px;margin-right: 20px;">
        <div class="col-12">
            <h6 class="heading-small" style="color:darkred">{{ 'USER_PROFILE_DELETE_AREA'|trans }}</h6>
            <p class="heading-small mb-4" style="color:darkred">{{ 'USER_PROFILE_DELETE_HINT'|trans|raw }}</p>
        </div>
    </div>
    <div class="card-body pt-0 pt-md-4">
        <a class="btn btn-block btn-danger del-user" href="javascript:void(0)">{{ 'USER_PROFILE_DELETE_CTA'|trans }}</a>
    </div>
</div>

templates/restricted/user-profile/partials/hints.profile.html.twig
<div class="card bg-secondary shadow">
    <div class="card-header bg-white border-0">
        <div class="row align-items-center">
            <div class="col-8">
                <h3 class="mb-0">{{ 'WELCOME'|trans }} {{ user.name }}</h3>
            </div>
        </div>
    </div>
    <div class="card-body">
        <p>{{ 'PROFILE_PAGE_HINT_1'|trans }}</p>
        <p>{{ 'PROFILE_PAGE_HINT_2'|trans }}</p>
        <p>{{ 'PROFILE_PAGE_HINT_3'|trans }}</p>
    </div>
</div>

templates/restricted/user-profile/partials/notifications-settings.html.twig
<div class="row align-items-center">
    <div class="col-8">
        <h6 class="heading-small text-muted mb-4">{{ 'PROFILE_PAGE_SUBTITLE_6'|trans }}</h6>
    </div>
    <div class="col-4 text-right">
        <a href="javascript:void(0)" class="btn btn-sm btn-success save-user">{{ 'PROFILE_PAGE_SAVE'|trans }}</a>
    </div>
</div>
<div class="pl-lg-4">

    <div class="row">
        <div class="col-lg-12">
            <div class="custom-control custom-switch">
                {{ form_widget(form.activities_email, {'attr': {'class': 'custom-control-input'}}) }}
                <label class="custom-control-label" for="user_activities_email">{{ 'PROFILE_PAGE_ACTIVITIES_EMAIL'|trans }}</label>
                <p class="profile-hint">{{ 'PROFILE_PAGE_ACTIVITIES_EMAIL_HINT'|trans }}</p>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="custom-control custom-switch">
                {{ form_widget(form.comments_email, {'attr': {'class': 'custom-control-input'}}) }}
                <label class="custom-control-label" for="user_comments_email">{{ 'PROFILE_PAGE_COMMENTS_EMAIL'|trans }}</label>
                <p class="profile-hint">{{ 'PROFILE_PAGE_COMMENTS_EMAIL_HINT'|trans }}</p>
            </div>
        </div>
    </div>
</div>

templates/restricted/user-profile/partials/password.profile.html.twig
<div class="card card-profile shadow">
    <div class="row align-items-center" style="margin-left: 10px;margin-top: 10px;margin-right: 20px;">
        <div class="col-8">
            <h6 class="heading-small" style="color:darkred">{{ 'USER_EDIT_PASSWORD_AREA'|trans }}</h6>
            <p class="heading-small mb-4" style="color:darkred">{{ 'USER_EDIT_PASSWORD_HINT'|trans }}</p>
        </div>
        <div class="col-4 text-right">
            <a href="javascript:void(0)" class="btn btn-sm btn-success save-user">{{ 'PROFILE_PAGE_SAVE'|trans }}</a>
        </div>
    </div>
    <div class="card-body pt-0 pt-md-4">
        <div class="row" >
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="form-control-label">{{ 'PASSWORD'|trans }}</label>
                    <div class="input-group">
                        {{ form_widget(form.plainPassword.first, {'attr': {'class': 'form-control'}}) }}
                        <button id="user_plainPassword_first-toggle-password" class="toggle-password" type="button" class="d-none" aria-label=""></button>
                    </div>
                    {{ form_errors(form.plainPassword.first) }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="form-control-label">{{ 'REPEAT_PASSWORD'|trans }}</label>
                    <div class="input-group">
                        {{ form_widget(form.plainPassword.second, {'attr': {'class': 'form-control'}}) }}
                        <button id="user_plainPassword_second-toggle-password" class="toggle-password" type="button" class="d-none" aria-label=""></button>
                    </div>
                    {{ form_errors(form.plainPassword.second) }}
                </div>
            </div>
        </div>
    </div>
</div>

templates/restricted/user-profile/partials/skills.profile.html.twig
<div class="card card-profile shadow">
    <div class="row align-items-center" style="margin-left: 10px;margin-top: 10px;margin-right: 20px;">
        <div class="col-8">
            <h6 class="heading-small text-muted mb-4">{{ 'PROFILE_PAGE_SUBTITLE_4'|trans }}</h6>
        </div>
        <div class="col-4 text-right">
            <a href="javascript:void(0)" class="btn btn-sm btn-success save-user">{{ 'PROFILE_PAGE_SAVE'|trans }}</a>
        </div>
    </div>
    <div class="card-body pt-0 pt-md-4">
        <h3 class="text-center">Skills</h3>
        <div class="text-left">
            {{ form_widget(form.skills, {'attr': {'class': ''}}) }}
        </div>
    </div>
</div>